#include "grammar_objects.h"

union Object String1 = { .String.type = String, .String.value = "grammar" };
union Object Identifier2 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object String3 = { .String.type = String, .String.value = "r" };
union Object Identifier4 = { .Identifier.type = Identifier, .Identifier.value = "root" };
union Object Assignment5 = { .Assignment.type = Assignment, .Assignment.variableName = &String3, .Assignment.ruleIdentifier = &Identifier4 };
union Object Sequence6 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier2, .Binary.rightExpression = &Assignment5 };
union Object Identifier7 = { .Identifier.type = Identifier, .Identifier.value = "declaration" };
union Object String8 = { .String.type = String, .String.value = "d" };
union Object Identifier9 = { .Identifier.type = Identifier, .Identifier.value = "definition" };
union Object Assignment10 = { .Assignment.type = Assignment, .Assignment.variableName = &String8, .Assignment.ruleIdentifier = &Identifier9 };
union Object Action11 = { .Action.type = Action, .Action.value = " addRuleDefinitionToGrammar(r, d); " };
union Object Sequence12 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment10, .Binary.rightExpression = &Action11 };
union Object Alternation13 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Identifier7, .Binary.rightExpression = &Sequence12 };
union Object Plus14 = { .Unary.type = Unary, .Unary.op = Plus, .Unary.expression = &Alternation13 };
union Object Sequence15 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence6, .Binary.rightExpression = &Plus14 };
union Object Identifier16 = { .Identifier.type = Identifier, .Identifier.value = "trailer" };
union Object Optional17 = { .Unary.type = Unary, .Unary.op = Optional, .Unary.expression = &Identifier16 };
union Object Sequence18 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence15, .Binary.rightExpression = &Optional17 };
union Object Identifier19 = { .Identifier.type = Identifier, .Identifier.value = "end-of-file" };
union Object Sequence20 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence18, .Binary.rightExpression = &Identifier19 };
union Object Action21 = { .Action.type = Action, .Action.value = " printTree(r); writeTree(r); " };
union Object Sequence22 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence20, .Binary.rightExpression = &Action21 };
union Object Definition23 = { .Definition.type = Definition, .Definition.name = &String1, .Definition.rule = &Sequence22 };

union Object String24 = { .String.type = String, .String.value = "root" };
union Object Action25 = { .Action.type = Action, .Action.value = " $$ = newGrammar(); " };
union Object Definition26 = { .Definition.type = Definition, .Definition.name = &String24, .Definition.rule = &Action25 };

union Object String27 = { .String.type = String, .String.value = "declaration" };
union Object String28 = { .String.type = String, .String.value = "%{" };
union Object Begin29 = { .Begin.type = Begin };
union Object Sequence30 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String28, .Binary.rightExpression = &Begin29 };
union Object String31 = { .String.type = String, .String.value = "%}" };
union Object Not32 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &String31 };
union Object Dot33 = { .Dot.type = Dot };
union Object Sequence34 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not32, .Binary.rightExpression = &Dot33 };
union Object Star35 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence34 };
union Object Sequence36 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence30, .Binary.rightExpression = &Star35 };
union Object End37 = { .End.type = End };
union Object Sequence38 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence36, .Binary.rightExpression = &End37 };
union Object Identifier39 = { .Identifier.type = Identifier, .Identifier.value = "RPERCENT" };
union Object Sequence40 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence38, .Binary.rightExpression = &Identifier39 };
union Object Definition41 = { .Definition.type = Definition, .Definition.name = &String27, .Definition.rule = &Sequence40 };

union Object String42 = { .String.type = String, .String.value = "trailer" };
union Object String43 = { .String.type = String, .String.value = "%%" };
union Object Begin44 = { .Begin.type = Begin };
union Object Sequence45 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String43, .Binary.rightExpression = &Begin44 };
union Object Dot46 = { .Dot.type = Dot };
union Object Star47 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Dot46 };
union Object Sequence48 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence45, .Binary.rightExpression = &Star47 };
union Object End49 = { .End.type = End };
union Object Sequence50 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence48, .Binary.rightExpression = &End49 };
union Object Definition51 = { .Definition.type = Definition, .Definition.name = &String42, .Definition.rule = &Sequence50 };

union Object String52 = { .String.type = String, .String.value = "definition" };
union Object String53 = { .String.type = String, .String.value = "i" };
union Object Identifier54 = { .Identifier.type = Identifier, .Identifier.value = "identifier" };
union Object Assignment55 = { .Assignment.type = Assignment, .Assignment.variableName = &String53, .Assignment.ruleIdentifier = &Identifier54 };
union Object Identifier56 = { .Identifier.type = Identifier, .Identifier.value = "EQUAL" };
union Object Sequence57 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment55, .Binary.rightExpression = &Identifier56 };
union Object String58 = { .String.type = String, .String.value = "e" };
union Object Identifier59 = { .Identifier.type = Identifier, .Identifier.value = "expression" };
union Object Assignment60 = { .Assignment.type = Assignment, .Assignment.variableName = &String58, .Assignment.ruleIdentifier = &Identifier59 };
union Object Sequence61 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence57, .Binary.rightExpression = &Assignment60 };
union Object Identifier62 = { .Identifier.type = Identifier, .Identifier.value = "SEMICOLON" };
union Object Optional63 = { .Unary.type = Unary, .Unary.op = Optional, .Unary.expression = &Identifier62 };
union Object Sequence64 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence61, .Binary.rightExpression = &Optional63 };
union Object Action65 = { .Action.type = Action, .Action.value = " $$ = newDefinition(i, e); " };
union Object Sequence66 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence64, .Binary.rightExpression = &Action65 };
union Object Definition67 = { .Definition.type = Definition, .Definition.name = &String52, .Definition.rule = &Sequence66 };

union Object String68 = { .String.type = String, .String.value = "expression" };
union Object String69 = { .String.type = String, .String.value = "s1" };
union Object Identifier70 = { .Identifier.type = Identifier, .Identifier.value = "sequence" };
union Object Assignment71 = { .Assignment.type = Assignment, .Assignment.variableName = &String69, .Assignment.ruleIdentifier = &Identifier70 };
union Object Identifier72 = { .Identifier.type = Identifier, .Identifier.value = "BAR" };
union Object String73 = { .String.type = String, .String.value = "s2" };
union Object Identifier74 = { .Identifier.type = Identifier, .Identifier.value = "sequence" };
union Object Assignment75 = { .Assignment.type = Assignment, .Assignment.variableName = &String73, .Assignment.ruleIdentifier = &Identifier74 };
union Object Sequence76 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier72, .Binary.rightExpression = &Assignment75 };
union Object Action77 = { .Action.type = Action, .Action.value = " s1 = newBinary(Alternation, s1, s2); " };
union Object Sequence78 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence76, .Binary.rightExpression = &Action77 };
union Object Star79 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence78 };
union Object Sequence80 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment71, .Binary.rightExpression = &Star79 };
union Object Action81 = { .Action.type = Action, .Action.value = " $$ = s1; " };
union Object Sequence82 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence80, .Binary.rightExpression = &Action81 };
union Object Definition83 = { .Definition.type = Definition, .Definition.name = &String68, .Definition.rule = &Sequence82 };

union Object String84 = { .String.type = String, .String.value = "sequence" };
union Object String85 = { .String.type = String, .String.value = "e" };
union Object Identifier86 = { .Identifier.type = Identifier, .Identifier.value = "error" };
union Object Assignment87 = { .Assignment.type = Assignment, .Assignment.variableName = &String85, .Assignment.ruleIdentifier = &Identifier86 };
union Object String88 = { .String.type = String, .String.value = "f" };
union Object Identifier89 = { .Identifier.type = Identifier, .Identifier.value = "error" };
union Object Assignment90 = { .Assignment.type = Assignment, .Assignment.variableName = &String88, .Assignment.ruleIdentifier = &Identifier89 };
union Object Action91 = { .Action.type = Action, .Action.value = " e = newBinary(Sequence, e, f); " };
union Object Sequence92 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment90, .Binary.rightExpression = &Action91 };
union Object Star93 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence92 };
union Object Sequence94 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment87, .Binary.rightExpression = &Star93 };
union Object Action95 = { .Action.type = Action, .Action.value = " $$ = e; " };
union Object Sequence96 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence94, .Binary.rightExpression = &Action95 };
union Object Definition97 = { .Definition.type = Definition, .Definition.name = &String84, .Definition.rule = &Sequence96 };

union Object String98 = { .String.type = String, .String.value = "error" };
union Object String99 = { .String.type = String, .String.value = "p" };
union Object Identifier100 = { .Identifier.type = Identifier, .Identifier.value = "prefix" };
union Object Assignment101 = { .Assignment.type = Assignment, .Assignment.variableName = &String99, .Assignment.ruleIdentifier = &Identifier100 };
union Object Identifier102 = { .Identifier.type = Identifier, .Identifier.value = "TILDE" };
union Object Identifier103 = { .Identifier.type = Identifier, .Identifier.value = "action" };
union Object Sequence104 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier102, .Binary.rightExpression = &Identifier103 };
union Object Optional105 = { .Unary.type = Unary, .Unary.op = Optional, .Unary.expression = &Sequence104 };
union Object Sequence106 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment101, .Binary.rightExpression = &Optional105 };
union Object Action107 = { .Action.type = Action, .Action.value = " $$ = p; " };
union Object Sequence108 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence106, .Binary.rightExpression = &Action107 };
union Object Definition109 = { .Definition.type = Definition, .Definition.name = &String98, .Definition.rule = &Sequence108 };

union Object String110 = { .String.type = String, .String.value = "prefix" };
union Object Identifier111 = { .Identifier.type = Identifier, .Identifier.value = "AND" };
union Object Identifier112 = { .Identifier.type = Identifier, .Identifier.value = "action" };
union Object Sequence113 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier111, .Binary.rightExpression = &Identifier112 };
union Object Identifier114 = { .Identifier.type = Identifier, .Identifier.value = "AND" };
union Object String115 = { .String.type = String, .String.value = "s" };
union Object Identifier116 = { .Identifier.type = Identifier, .Identifier.value = "suffix" };
union Object Assignment117 = { .Assignment.type = Assignment, .Assignment.variableName = &String115, .Assignment.ruleIdentifier = &Identifier116 };
union Object Sequence118 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier114, .Binary.rightExpression = &Assignment117 };
union Object Action119 = { .Action.type = Action, .Action.value = " $$ = newUnary(And, s); " };
union Object Sequence120 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence118, .Binary.rightExpression = &Action119 };
union Object Identifier121 = { .Identifier.type = Identifier, .Identifier.value = "NOT" };
union Object String122 = { .String.type = String, .String.value = "s" };
union Object Identifier123 = { .Identifier.type = Identifier, .Identifier.value = "suffix" };
union Object Assignment124 = { .Assignment.type = Assignment, .Assignment.variableName = &String122, .Assignment.ruleIdentifier = &Identifier123 };
union Object Sequence125 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier121, .Binary.rightExpression = &Assignment124 };
union Object Action126 = { .Action.type = Action, .Action.value = " $$ = newUnary(Not, s); " };
union Object Sequence127 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence125, .Binary.rightExpression = &Action126 };
union Object Alternation128 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence120, .Binary.rightExpression = &Sequence127 };
union Object String129 = { .String.type = String, .String.value = "s" };
union Object Identifier130 = { .Identifier.type = Identifier, .Identifier.value = "suffix" };
union Object Assignment131 = { .Assignment.type = Assignment, .Assignment.variableName = &String129, .Assignment.ruleIdentifier = &Identifier130 };
union Object Action132 = { .Action.type = Action, .Action.value = " $$ = s; " };
union Object Sequence133 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment131, .Binary.rightExpression = &Action132 };
union Object Alternation134 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation128, .Binary.rightExpression = &Sequence133 };
union Object Alternation135 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence113, .Binary.rightExpression = &Alternation134 };
union Object Definition136 = { .Definition.type = Definition, .Definition.name = &String110, .Definition.rule = &Alternation135 };

union Object String137 = { .String.type = String, .String.value = "suffix" };
union Object String138 = { .String.type = String, .String.value = "p" };
union Object Identifier139 = { .Identifier.type = Identifier, .Identifier.value = "primary" };
union Object Assignment140 = { .Assignment.type = Assignment, .Assignment.variableName = &String138, .Assignment.ruleIdentifier = &Identifier139 };
union Object Identifier141 = { .Identifier.type = Identifier, .Identifier.value = "QUERY" };
union Object Action142 = { .Action.type = Action, .Action.value = " p = newUnary(Optional, p); " };
union Object Sequence143 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier141, .Binary.rightExpression = &Action142 };
union Object Identifier144 = { .Identifier.type = Identifier, .Identifier.value = "STAR" };
union Object Action145 = { .Action.type = Action, .Action.value = " p = newUnary(Star, p); " };
union Object Sequence146 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier144, .Binary.rightExpression = &Action145 };
union Object Alternation147 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence143, .Binary.rightExpression = &Sequence146 };
union Object Identifier148 = { .Identifier.type = Identifier, .Identifier.value = "PLUS" };
union Object Action149 = { .Action.type = Action, .Action.value = " p = newUnary(Plus, p); " };
union Object Sequence150 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier148, .Binary.rightExpression = &Action149 };
union Object Alternation151 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation147, .Binary.rightExpression = &Sequence150 };
union Object Optional152 = { .Unary.type = Unary, .Unary.op = Optional, .Unary.expression = &Alternation151 };
union Object Sequence153 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment140, .Binary.rightExpression = &Optional152 };
union Object Action154 = { .Action.type = Action, .Action.value = " $$ = p; " };
union Object Sequence155 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence153, .Binary.rightExpression = &Action154 };
union Object Definition156 = { .Definition.type = Definition, .Definition.name = &String137, .Definition.rule = &Sequence155 };

union Object String157 = { .String.type = String, .String.value = "primary" };
union Object String158 = { .String.type = String, .String.value = "i1" };
union Object Identifier159 = { .Identifier.type = Identifier, .Identifier.value = "identifier" };
union Object Assignment160 = { .Assignment.type = Assignment, .Assignment.variableName = &String158, .Assignment.ruleIdentifier = &Identifier159 };
union Object Identifier161 = { .Identifier.type = Identifier, .Identifier.value = "COLON" };
union Object Sequence162 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment160, .Binary.rightExpression = &Identifier161 };
union Object String163 = { .String.type = String, .String.value = "i2" };
union Object Identifier164 = { .Identifier.type = Identifier, .Identifier.value = "ruleCallIdent" };
union Object Assignment165 = { .Assignment.type = Assignment, .Assignment.variableName = &String163, .Assignment.ruleIdentifier = &Identifier164 };
union Object Sequence166 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence162, .Binary.rightExpression = &Assignment165 };
union Object Identifier167 = { .Identifier.type = Identifier, .Identifier.value = "EQUAL" };
union Object Not168 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &Identifier167 };
union Object Sequence169 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence166, .Binary.rightExpression = &Not168 };
union Object Action170 = { .Action.type = Action, .Action.value = " $$ = newAssignment(i1, i2) " };
union Object Sequence171 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence169, .Binary.rightExpression = &Action170 };
union Object String172 = { .String.type = String, .String.value = "i" };
union Object Identifier173 = { .Identifier.type = Identifier, .Identifier.value = "ruleCallIdent" };
union Object Assignment174 = { .Assignment.type = Assignment, .Assignment.variableName = &String172, .Assignment.ruleIdentifier = &Identifier173 };
union Object Identifier175 = { .Identifier.type = Identifier, .Identifier.value = "EQUAL" };
union Object Not176 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &Identifier175 };
union Object Sequence177 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment174, .Binary.rightExpression = &Not176 };
union Object Action178 = { .Action.type = Action, .Action.value = " $$ = i; " };
union Object Sequence179 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence177, .Binary.rightExpression = &Action178 };
union Object Alternation180 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence171, .Binary.rightExpression = &Sequence179 };
union Object Identifier181 = { .Identifier.type = Identifier, .Identifier.value = "OPEN" };
union Object String182 = { .String.type = String, .String.value = "e" };
union Object Identifier183 = { .Identifier.type = Identifier, .Identifier.value = "expression" };
union Object Assignment184 = { .Assignment.type = Assignment, .Assignment.variableName = &String182, .Assignment.ruleIdentifier = &Identifier183 };
union Object Sequence185 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier181, .Binary.rightExpression = &Assignment184 };
union Object Identifier186 = { .Identifier.type = Identifier, .Identifier.value = "CLOSE" };
union Object Sequence187 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence185, .Binary.rightExpression = &Identifier186 };
union Object Action188 = { .Action.type = Action, .Action.value = " $$ = e; " };
union Object Sequence189 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence187, .Binary.rightExpression = &Action188 };
union Object Alternation190 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation180, .Binary.rightExpression = &Sequence189 };
union Object String191 = { .String.type = String, .String.value = "l" };
union Object Identifier192 = { .Identifier.type = Identifier, .Identifier.value = "literal" };
union Object Assignment193 = { .Assignment.type = Assignment, .Assignment.variableName = &String191, .Assignment.ruleIdentifier = &Identifier192 };
union Object Action194 = { .Action.type = Action, .Action.value = " $$ = l; " };
union Object Sequence195 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment193, .Binary.rightExpression = &Action194 };
union Object Alternation196 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation190, .Binary.rightExpression = &Sequence195 };
union Object String197 = { .String.type = String, .String.value = "c" };
union Object Identifier198 = { .Identifier.type = Identifier, .Identifier.value = "class" };
union Object Assignment199 = { .Assignment.type = Assignment, .Assignment.variableName = &String197, .Assignment.ruleIdentifier = &Identifier198 };
union Object Action200 = { .Action.type = Action, .Action.value = " $$ = c; " };
union Object Sequence201 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment199, .Binary.rightExpression = &Action200 };
union Object Alternation202 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation196, .Binary.rightExpression = &Sequence201 };
union Object Identifier203 = { .Identifier.type = Identifier, .Identifier.value = "DOT" };
union Object Action204 = { .Action.type = Action, .Action.value = " $$ = newDot(); " };
union Object Sequence205 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier203, .Binary.rightExpression = &Action204 };
union Object Alternation206 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation202, .Binary.rightExpression = &Sequence205 };
union Object String207 = { .String.type = String, .String.value = "a" };
union Object Identifier208 = { .Identifier.type = Identifier, .Identifier.value = "action" };
union Object Assignment209 = { .Assignment.type = Assignment, .Assignment.variableName = &String207, .Assignment.ruleIdentifier = &Identifier208 };
union Object Action210 = { .Action.type = Action, .Action.value = " $$ = a; " };
union Object Sequence211 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Assignment209, .Binary.rightExpression = &Action210 };
union Object Alternation212 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation206, .Binary.rightExpression = &Sequence211 };
union Object Identifier213 = { .Identifier.type = Identifier, .Identifier.value = "BEGIN" };
union Object Action214 = { .Action.type = Action, .Action.value = " $$ = newBegin(); " };
union Object Sequence215 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier213, .Binary.rightExpression = &Action214 };
union Object Alternation216 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation212, .Binary.rightExpression = &Sequence215 };
union Object Identifier217 = { .Identifier.type = Identifier, .Identifier.value = "END" };
union Object Action218 = { .Action.type = Action, .Action.value = " $$ = newEnd(); " };
union Object Sequence219 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier217, .Binary.rightExpression = &Action218 };
union Object Alternation220 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation216, .Binary.rightExpression = &Sequence219 };
union Object Definition221 = { .Definition.type = Definition, .Definition.name = &String157, .Definition.rule = &Alternation220 };

union Object String222 = { .String.type = String, .String.value = "identifier" };
union Object Begin223 = { .Begin.type = Begin };
union Object CharacterClass224 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "-a-zA-Z_" };
union Object Sequence225 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Begin223, .Binary.rightExpression = &CharacterClass224 };
union Object CharacterClass226 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "-a-zA-Z_0-9" };
union Object Star227 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &CharacterClass226 };
union Object Sequence228 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence225, .Binary.rightExpression = &Star227 };
union Object End229 = { .End.type = End };
union Object Sequence230 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence228, .Binary.rightExpression = &End229 };
union Object Identifier231 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence232 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence230, .Binary.rightExpression = &Identifier231 };
union Object Action233 = { .Action.type = Action, .Action.value = " $$ = newString(yytext); " };
union Object Sequence234 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence232, .Binary.rightExpression = &Action233 };
union Object Definition235 = { .Definition.type = Definition, .Definition.name = &String222, .Definition.rule = &Sequence234 };

union Object String236 = { .String.type = String, .String.value = "ruleCallIdent" };
union Object Begin237 = { .Begin.type = Begin };
union Object CharacterClass238 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "-a-zA-Z_" };
union Object Sequence239 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Begin237, .Binary.rightExpression = &CharacterClass238 };
union Object CharacterClass240 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "-a-zA-Z_0-9" };
union Object Star241 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &CharacterClass240 };
union Object Sequence242 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence239, .Binary.rightExpression = &Star241 };
union Object End243 = { .End.type = End };
union Object Sequence244 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence242, .Binary.rightExpression = &End243 };
union Object Identifier245 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence246 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence244, .Binary.rightExpression = &Identifier245 };
union Object Action247 = { .Action.type = Action, .Action.value = " $$ = newIdentifier(yytext); " };
union Object Sequence248 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence246, .Binary.rightExpression = &Action247 };
union Object Definition249 = { .Definition.type = Definition, .Definition.name = &String236, .Definition.rule = &Sequence248 };

union Object String250 = { .String.type = String, .String.value = "literal" };
union Object CharacterClass251 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "\'" };
union Object Begin252 = { .Begin.type = Begin };
union Object Sequence253 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &CharacterClass251, .Binary.rightExpression = &Begin252 };
union Object CharacterClass254 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "\'" };
union Object Not255 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &CharacterClass254 };
union Object Identifier256 = { .Identifier.type = Identifier, .Identifier.value = "char" };
union Object Sequence257 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not255, .Binary.rightExpression = &Identifier256 };
union Object Star258 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence257 };
union Object Sequence259 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence253, .Binary.rightExpression = &Star258 };
union Object End260 = { .End.type = End };
union Object Sequence261 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence259, .Binary.rightExpression = &End260 };
union Object CharacterClass262 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "\'" };
union Object Sequence263 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence261, .Binary.rightExpression = &CharacterClass262 };
union Object Identifier264 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence265 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence263, .Binary.rightExpression = &Identifier264 };
union Object Action266 = { .Action.type = Action, .Action.value = " $$ = newString(yytext); " };
union Object Sequence267 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence265, .Binary.rightExpression = &Action266 };
union Object CharacterClass268 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "\"" };
union Object Begin269 = { .Begin.type = Begin };
union Object Sequence270 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &CharacterClass268, .Binary.rightExpression = &Begin269 };
union Object CharacterClass271 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "\"" };
union Object Not272 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &CharacterClass271 };
union Object Identifier273 = { .Identifier.type = Identifier, .Identifier.value = "char" };
union Object Sequence274 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not272, .Binary.rightExpression = &Identifier273 };
union Object Star275 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence274 };
union Object Sequence276 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence270, .Binary.rightExpression = &Star275 };
union Object End277 = { .End.type = End };
union Object Sequence278 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence276, .Binary.rightExpression = &End277 };
union Object CharacterClass279 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "\"" };
union Object Sequence280 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence278, .Binary.rightExpression = &CharacterClass279 };
union Object Identifier281 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence282 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence280, .Binary.rightExpression = &Identifier281 };
union Object Alternation283 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence267, .Binary.rightExpression = &Sequence282 };
union Object Definition284 = { .Definition.type = Definition, .Definition.name = &String250, .Definition.rule = &Alternation283 };

union Object String285 = { .String.type = String, .String.value = "class" };
union Object String286 = { .String.type = String, .String.value = "[" };
union Object Begin287 = { .Begin.type = Begin };
union Object Sequence288 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String286, .Binary.rightExpression = &Begin287 };
union Object String289 = { .String.type = String, .String.value = "]" };
union Object Not290 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &String289 };
union Object Identifier291 = { .Identifier.type = Identifier, .Identifier.value = "range" };
union Object Sequence292 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not290, .Binary.rightExpression = &Identifier291 };
union Object Star293 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence292 };
union Object Sequence294 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence288, .Binary.rightExpression = &Star293 };
union Object End295 = { .End.type = End };
union Object Sequence296 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence294, .Binary.rightExpression = &End295 };
union Object String297 = { .String.type = String, .String.value = "]" };
union Object Sequence298 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence296, .Binary.rightExpression = &String297 };
union Object Identifier299 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence300 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence298, .Binary.rightExpression = &Identifier299 };
union Object Action301 = { .Action.type = Action, .Action.value = " $$ = newCharacterClass(yytext); " };
union Object Sequence302 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence300, .Binary.rightExpression = &Action301 };
union Object Definition303 = { .Definition.type = Definition, .Definition.name = &String285, .Definition.rule = &Sequence302 };

union Object String304 = { .String.type = String, .String.value = "range" };
union Object Identifier305 = { .Identifier.type = Identifier, .Identifier.value = "char" };
union Object String306 = { .String.type = String, .String.value = "-" };
union Object Sequence307 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Identifier305, .Binary.rightExpression = &String306 };
union Object Identifier308 = { .Identifier.type = Identifier, .Identifier.value = "char" };
union Object Sequence309 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence307, .Binary.rightExpression = &Identifier308 };
union Object Identifier310 = { .Identifier.type = Identifier, .Identifier.value = "char" };
union Object Alternation311 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence309, .Binary.rightExpression = &Identifier310 };
union Object Definition312 = { .Definition.type = Definition, .Definition.name = &String304, .Definition.rule = &Alternation311 };

union Object String313 = { .String.type = String, .String.value = "char" };
union Object String314 = { .String.type = String, .String.value = "\\\\" };
union Object CharacterClass315 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "abefnrtv\'\"\\[\\]\\\\" };
union Object Sequence316 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String314, .Binary.rightExpression = &CharacterClass315 };
union Object String317 = { .String.type = String, .String.value = "\\\\" };
union Object CharacterClass318 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "0-3" };
union Object Sequence319 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String317, .Binary.rightExpression = &CharacterClass318 };
union Object CharacterClass320 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "0-7" };
union Object Sequence321 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence319, .Binary.rightExpression = &CharacterClass320 };
union Object CharacterClass322 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "0-7" };
union Object Sequence323 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence321, .Binary.rightExpression = &CharacterClass322 };
union Object Alternation324 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence316, .Binary.rightExpression = &Sequence323 };
union Object String325 = { .String.type = String, .String.value = "\\\\" };
union Object CharacterClass326 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "0-7" };
union Object Sequence327 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String325, .Binary.rightExpression = &CharacterClass326 };
union Object CharacterClass328 = { .CharacterClass.type = CharacterClass, .CharacterClass.value = "0-7" };
union Object Optional329 = { .Unary.type = Unary, .Unary.op = Optional, .Unary.expression = &CharacterClass328 };
union Object Sequence330 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence327, .Binary.rightExpression = &Optional329 };
union Object Alternation331 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation324, .Binary.rightExpression = &Sequence330 };
union Object String332 = { .String.type = String, .String.value = "\\\\" };
union Object Not333 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &String332 };
union Object Dot334 = { .Dot.type = Dot };
union Object Sequence335 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not333, .Binary.rightExpression = &Dot334 };
union Object Alternation336 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation331, .Binary.rightExpression = &Sequence335 };
union Object Definition337 = { .Definition.type = Definition, .Definition.name = &String313, .Definition.rule = &Alternation336 };

union Object String338 = { .String.type = String, .String.value = "action" };
union Object String339 = { .String.type = String, .String.value = "{" };
union Object Begin340 = { .Begin.type = Begin };
union Object Sequence341 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String339, .Binary.rightExpression = &Begin340 };
union Object Identifier342 = { .Identifier.type = Identifier, .Identifier.value = "braces" };
union Object Star343 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Identifier342 };
union Object Sequence344 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence341, .Binary.rightExpression = &Star343 };
union Object End345 = { .End.type = End };
union Object Sequence346 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence344, .Binary.rightExpression = &End345 };
union Object String347 = { .String.type = String, .String.value = "}" };
union Object Sequence348 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence346, .Binary.rightExpression = &String347 };
union Object Identifier349 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence350 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence348, .Binary.rightExpression = &Identifier349 };
union Object Action351 = { .Action.type = Action, .Action.value = " $$ = newAction(yytext); " };
union Object Sequence352 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence350, .Binary.rightExpression = &Action351 };
union Object Definition353 = { .Definition.type = Definition, .Definition.name = &String338, .Definition.rule = &Sequence352 };

union Object String354 = { .String.type = String, .String.value = "braces" };
union Object String355 = { .String.type = String, .String.value = "{" };
union Object Identifier356 = { .Identifier.type = Identifier, .Identifier.value = "braces" };
union Object Star357 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Identifier356 };
union Object Sequence358 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String355, .Binary.rightExpression = &Star357 };
union Object String359 = { .String.type = String, .String.value = "}" };
union Object Sequence360 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence358, .Binary.rightExpression = &String359 };
union Object String361 = { .String.type = String, .String.value = "}" };
union Object Not362 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &String361 };
union Object Dot363 = { .Dot.type = Dot };
union Object Sequence364 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not362, .Binary.rightExpression = &Dot363 };
union Object Alternation365 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Sequence360, .Binary.rightExpression = &Sequence364 };
union Object Definition366 = { .Definition.type = Definition, .Definition.name = &String354, .Definition.rule = &Alternation365 };

union Object String367 = { .String.type = String, .String.value = "EQUAL" };
union Object String368 = { .String.type = String, .String.value = "=" };
union Object Identifier369 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence370 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String368, .Binary.rightExpression = &Identifier369 };
union Object Definition371 = { .Definition.type = Definition, .Definition.name = &String367, .Definition.rule = &Sequence370 };

union Object String372 = { .String.type = String, .String.value = "COLON" };
union Object String373 = { .String.type = String, .String.value = ":" };
union Object Identifier374 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence375 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String373, .Binary.rightExpression = &Identifier374 };
union Object Definition376 = { .Definition.type = Definition, .Definition.name = &String372, .Definition.rule = &Sequence375 };

union Object String377 = { .String.type = String, .String.value = "SEMICOLON" };
union Object String378 = { .String.type = String, .String.value = ";" };
union Object Identifier379 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence380 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String378, .Binary.rightExpression = &Identifier379 };
union Object Definition381 = { .Definition.type = Definition, .Definition.name = &String377, .Definition.rule = &Sequence380 };

union Object String382 = { .String.type = String, .String.value = "BAR" };
union Object String383 = { .String.type = String, .String.value = "|" };
union Object Identifier384 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence385 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String383, .Binary.rightExpression = &Identifier384 };
union Object Definition386 = { .Definition.type = Definition, .Definition.name = &String382, .Definition.rule = &Sequence385 };

union Object String387 = { .String.type = String, .String.value = "AND" };
union Object String388 = { .String.type = String, .String.value = "&" };
union Object Identifier389 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence390 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String388, .Binary.rightExpression = &Identifier389 };
union Object Definition391 = { .Definition.type = Definition, .Definition.name = &String387, .Definition.rule = &Sequence390 };

union Object String392 = { .String.type = String, .String.value = "NOT" };
union Object String393 = { .String.type = String, .String.value = "!" };
union Object Identifier394 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence395 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String393, .Binary.rightExpression = &Identifier394 };
union Object Definition396 = { .Definition.type = Definition, .Definition.name = &String392, .Definition.rule = &Sequence395 };

union Object String397 = { .String.type = String, .String.value = "QUERY" };
union Object String398 = { .String.type = String, .String.value = "?" };
union Object Identifier399 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence400 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String398, .Binary.rightExpression = &Identifier399 };
union Object Definition401 = { .Definition.type = Definition, .Definition.name = &String397, .Definition.rule = &Sequence400 };

union Object String402 = { .String.type = String, .String.value = "STAR" };
union Object String403 = { .String.type = String, .String.value = "*" };
union Object Identifier404 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence405 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String403, .Binary.rightExpression = &Identifier404 };
union Object Definition406 = { .Definition.type = Definition, .Definition.name = &String402, .Definition.rule = &Sequence405 };

union Object String407 = { .String.type = String, .String.value = "PLUS" };
union Object String408 = { .String.type = String, .String.value = "+" };
union Object Identifier409 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence410 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String408, .Binary.rightExpression = &Identifier409 };
union Object Definition411 = { .Definition.type = Definition, .Definition.name = &String407, .Definition.rule = &Sequence410 };

union Object String412 = { .String.type = String, .String.value = "OPEN" };
union Object String413 = { .String.type = String, .String.value = "(" };
union Object Identifier414 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence415 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String413, .Binary.rightExpression = &Identifier414 };
union Object Definition416 = { .Definition.type = Definition, .Definition.name = &String412, .Definition.rule = &Sequence415 };

union Object String417 = { .String.type = String, .String.value = "CLOSE" };
union Object String418 = { .String.type = String, .String.value = ")" };
union Object Identifier419 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence420 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String418, .Binary.rightExpression = &Identifier419 };
union Object Definition421 = { .Definition.type = Definition, .Definition.name = &String417, .Definition.rule = &Sequence420 };

union Object String422 = { .String.type = String, .String.value = "DOT" };
union Object String423 = { .String.type = String, .String.value = "." };
union Object Identifier424 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence425 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String423, .Binary.rightExpression = &Identifier424 };
union Object Definition426 = { .Definition.type = Definition, .Definition.name = &String422, .Definition.rule = &Sequence425 };

union Object String427 = { .String.type = String, .String.value = "BEGIN" };
union Object String428 = { .String.type = String, .String.value = "<" };
union Object Identifier429 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence430 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String428, .Binary.rightExpression = &Identifier429 };
union Object Definition431 = { .Definition.type = Definition, .Definition.name = &String427, .Definition.rule = &Sequence430 };

union Object String432 = { .String.type = String, .String.value = "END" };
union Object String433 = { .String.type = String, .String.value = ">" };
union Object Identifier434 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence435 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String433, .Binary.rightExpression = &Identifier434 };
union Object Definition436 = { .Definition.type = Definition, .Definition.name = &String432, .Definition.rule = &Sequence435 };

union Object String437 = { .String.type = String, .String.value = "TILDE" };
union Object String438 = { .String.type = String, .String.value = "~" };
union Object Identifier439 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence440 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String438, .Binary.rightExpression = &Identifier439 };
union Object Definition441 = { .Definition.type = Definition, .Definition.name = &String437, .Definition.rule = &Sequence440 };

union Object String442 = { .String.type = String, .String.value = "RPERCENT" };
union Object String443 = { .String.type = String, .String.value = "%}" };
union Object Identifier444 = { .Identifier.type = Identifier, .Identifier.value = "-" };
union Object Sequence445 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String443, .Binary.rightExpression = &Identifier444 };
union Object Definition446 = { .Definition.type = Definition, .Definition.name = &String442, .Definition.rule = &Sequence445 };

union Object String447 = { .String.type = String, .String.value = "-" };
union Object Identifier448 = { .Identifier.type = Identifier, .Identifier.value = "space" };
union Object Identifier449 = { .Identifier.type = Identifier, .Identifier.value = "comment" };
union Object Alternation450 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Identifier448, .Binary.rightExpression = &Identifier449 };
union Object Star451 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Alternation450 };
union Object Definition452 = { .Definition.type = Definition, .Definition.name = &String447, .Definition.rule = &Star451 };

union Object String453 = { .String.type = String, .String.value = "space" };
union Object String454 = { .String.type = String, .String.value = " " };
union Object String455 = { .String.type = String, .String.value = "\\t" };
union Object Alternation456 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &String454, .Binary.rightExpression = &String455 };
union Object Identifier457 = { .Identifier.type = Identifier, .Identifier.value = "end-of-line" };
union Object Alternation458 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation456, .Binary.rightExpression = &Identifier457 };
union Object Definition459 = { .Definition.type = Definition, .Definition.name = &String453, .Definition.rule = &Alternation458 };

union Object String460 = { .String.type = String, .String.value = "comment" };
union Object String461 = { .String.type = String, .String.value = "#" };
union Object Identifier462 = { .Identifier.type = Identifier, .Identifier.value = "end-of-line" };
union Object Not463 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &Identifier462 };
union Object Dot464 = { .Dot.type = Dot };
union Object Sequence465 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Not463, .Binary.rightExpression = &Dot464 };
union Object Star466 = { .Unary.type = Unary, .Unary.op = Star, .Unary.expression = &Sequence465 };
union Object Sequence467 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &String461, .Binary.rightExpression = &Star466 };
union Object Identifier468 = { .Identifier.type = Identifier, .Identifier.value = "end-of-line" };
union Object Sequence469 = { .Binary.type = Binary, .Binary.op = Sequence, .Binary.leftExpression = &Sequence467, .Binary.rightExpression = &Identifier468 };
union Object Definition470 = { .Definition.type = Definition, .Definition.name = &String460, .Definition.rule = &Sequence469 };

union Object String471 = { .String.type = String, .String.value = "end-of-line" };
union Object String472 = { .String.type = String, .String.value = "\\r\\n" };
union Object String473 = { .String.type = String, .String.value = "\\n" };
union Object Alternation474 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &String472, .Binary.rightExpression = &String473 };
union Object String475 = { .String.type = String, .String.value = "\\r" };
union Object Alternation476 = { .Binary.type = Binary, .Binary.op = Alternation, .Binary.leftExpression = &Alternation474, .Binary.rightExpression = &String475 };
union Object Definition477 = { .Definition.type = Definition, .Definition.name = &String471, .Definition.rule = &Alternation476 };

union Object String478 = { .String.type = String, .String.value = "end-of-file" };
union Object Dot479 = { .Dot.type = Dot };
union Object Not480 = { .Unary.type = Unary, .Unary.op = Not, .Unary.expression = &Dot479 };
union Object Definition481 = { .Definition.type = Definition, .Definition.name = &String478, .Definition.rule = &Not480 };

List definitions = { .size = 42, .used = 40, .data = { &Definition23, &Definition26, &Definition41, &Definition51, &Definition67, &Definition83, &Definition97, &Definition109, &Definition136, &Definition156, &Definition221, &Definition235, &Definition249, &Definition284, &Definition303, &Definition312, &Definition337, &Definition353, &Definition366, &Definition371, &Definition376, &Definition381, &Definition386, &Definition391, &Definition396, &Definition401, &Definition406, &Definition411, &Definition416, &Definition421, &Definition426, &Definition431, &Definition436, &Definition441, &Definition446, &Definition452, &Definition459, &Definition470, &Definition477, &Definition481, } };

union Object grammar = { .Grammar.type = Grammar, .Grammar.definitions = &definitions };

oop getGrammar() {
	 return &grammar;
}

