#include "grammar_objects.h"

oop getGrammar() {
	oop grammar = newGrammar();
	oop Identifier1 = newIdentifier("grammar");
	oop Identifier2 = newIdentifier("-");
	oop Identifier3 = newIdentifier("r");
	oop Identifier4 = newIdentifier("root");
	oop Assignment5 = newBinary(Assignment, Identifier3, Identifier4);
	oop Sequence6 = newBinary(Sequence, Identifier2, Assignment5);
	oop Identifier7 = newIdentifier("declaration");
	oop Identifier8 = newIdentifier("d");
	oop Identifier9 = newIdentifier("definition");
	oop Assignment10 = newBinary(Assignment, Identifier8, Identifier9);
	oop Action11 = newAction(" addRuleDefinitionToGrammar(r, d); ");
	oop Sequence12 = newBinary(Sequence, Assignment10, Action11);
	oop Alternation13 = newBinary(Alternation, Identifier7, Sequence12);
	oop Plus14 = newUnary(Plus, Alternation13);
	oop Sequence15 = newBinary(Sequence, Sequence6, Plus14);
	oop Identifier16 = newIdentifier("trailer");
	oop Optional17 = newUnary(Optional, Identifier16);
	oop Sequence18 = newBinary(Sequence, Sequence15, Optional17);
	oop Identifier19 = newIdentifier("end-of-file");
	oop Sequence20 = newBinary(Sequence, Sequence18, Identifier19);
	oop Action21 = newAction(" printTree(r); writeTree(r); ");
	oop Sequence22 = newBinary(Sequence, Sequence20, Action21);
	oop Definition23 = newBinary(Definition, Identifier1, Sequence22);
	addRuleDefinitionToGrammar(grammar, Definition23);

	oop Identifier24 = newIdentifier("root");
	oop Action25 = newAction(" $$ = newGrammar(); ");
	oop Definition26 = newBinary(Definition, Identifier24, Action25);
	addRuleDefinitionToGrammar(grammar, Definition26);

	oop Identifier27 = newIdentifier("declaration");
	oop String28 = newString("%{");
	oop Begin29 = newBegin();
	oop Sequence30 = newBinary(Sequence, String28, Begin29);
	oop String31 = newString("%}");
	oop Not32 = newUnary(Not, String31);
	oop Dot33 = newDot();
	oop Sequence34 = newBinary(Sequence, Not32, Dot33);
	oop Star35 = newUnary(Star, Sequence34);
	oop Sequence36 = newBinary(Sequence, Sequence30, Star35);
	oop End37 = newEnd();
	oop Sequence38 = newBinary(Sequence, Sequence36, End37);
	oop Identifier39 = newIdentifier("RPERCENT");
	oop Sequence40 = newBinary(Sequence, Sequence38, Identifier39);
	oop Definition41 = newBinary(Definition, Identifier27, Sequence40);
	addRuleDefinitionToGrammar(grammar, Definition41);

	oop Identifier42 = newIdentifier("trailer");
	oop String43 = newString("%%");
	oop Begin44 = newBegin();
	oop Sequence45 = newBinary(Sequence, String43, Begin44);
	oop Dot46 = newDot();
	oop Star47 = newUnary(Star, Dot46);
	oop Sequence48 = newBinary(Sequence, Sequence45, Star47);
	oop End49 = newEnd();
	oop Sequence50 = newBinary(Sequence, Sequence48, End49);
	oop Definition51 = newBinary(Definition, Identifier42, Sequence50);
	addRuleDefinitionToGrammar(grammar, Definition51);

	oop Identifier52 = newIdentifier("definition");
	oop Identifier53 = newIdentifier("i");
	oop Identifier54 = newIdentifier("identifier");
	oop Assignment55 = newBinary(Assignment, Identifier53, Identifier54);
	oop Identifier56 = newIdentifier("EQUAL");
	oop Sequence57 = newBinary(Sequence, Assignment55, Identifier56);
	oop Identifier58 = newIdentifier("e");
	oop Identifier59 = newIdentifier("expression");
	oop Assignment60 = newBinary(Assignment, Identifier58, Identifier59);
	oop Sequence61 = newBinary(Sequence, Sequence57, Assignment60);
	oop Identifier62 = newIdentifier("SEMICOLON");
	oop Optional63 = newUnary(Optional, Identifier62);
	oop Sequence64 = newBinary(Sequence, Sequence61, Optional63);
	oop Action65 = newAction(" $$ = newBinary(Definition, i, e); ");
	oop Sequence66 = newBinary(Sequence, Sequence64, Action65);
	oop Definition67 = newBinary(Definition, Identifier52, Sequence66);
	addRuleDefinitionToGrammar(grammar, Definition67);

	oop Identifier68 = newIdentifier("expression");
	oop Identifier69 = newIdentifier("s1");
	oop Identifier70 = newIdentifier("sequence");
	oop Assignment71 = newBinary(Assignment, Identifier69, Identifier70);
	oop Identifier72 = newIdentifier("BAR");
	oop Identifier73 = newIdentifier("s2");
	oop Identifier74 = newIdentifier("sequence");
	oop Assignment75 = newBinary(Assignment, Identifier73, Identifier74);
	oop Sequence76 = newBinary(Sequence, Identifier72, Assignment75);
	oop Action77 = newAction(" s1 = newBinary(Alternation, s1, s2); ");
	oop Sequence78 = newBinary(Sequence, Sequence76, Action77);
	oop Star79 = newUnary(Star, Sequence78);
	oop Sequence80 = newBinary(Sequence, Assignment71, Star79);
	oop Action81 = newAction(" $$ = s1; ");
	oop Sequence82 = newBinary(Sequence, Sequence80, Action81);
	oop Definition83 = newBinary(Definition, Identifier68, Sequence82);
	addRuleDefinitionToGrammar(grammar, Definition83);

	oop Identifier84 = newIdentifier("sequence");
	oop Identifier85 = newIdentifier("e");
	oop Identifier86 = newIdentifier("error");
	oop Assignment87 = newBinary(Assignment, Identifier85, Identifier86);
	oop Identifier88 = newIdentifier("f");
	oop Identifier89 = newIdentifier("error");
	oop Assignment90 = newBinary(Assignment, Identifier88, Identifier89);
	oop Action91 = newAction(" e = newBinary(Sequence, e, f); ");
	oop Sequence92 = newBinary(Sequence, Assignment90, Action91);
	oop Star93 = newUnary(Star, Sequence92);
	oop Sequence94 = newBinary(Sequence, Assignment87, Star93);
	oop Action95 = newAction(" $$ = e; ");
	oop Sequence96 = newBinary(Sequence, Sequence94, Action95);
	oop Definition97 = newBinary(Definition, Identifier84, Sequence96);
	addRuleDefinitionToGrammar(grammar, Definition97);

	oop Identifier98 = newIdentifier("error");
	oop Identifier99 = newIdentifier("p");
	oop Identifier100 = newIdentifier("prefix");
	oop Assignment101 = newBinary(Assignment, Identifier99, Identifier100);
	oop Identifier102 = newIdentifier("TILDE");
	oop Identifier103 = newIdentifier("action");
	oop Sequence104 = newBinary(Sequence, Identifier102, Identifier103);
	oop Optional105 = newUnary(Optional, Sequence104);
	oop Sequence106 = newBinary(Sequence, Assignment101, Optional105);
	oop Action107 = newAction(" $$ = p; ");
	oop Sequence108 = newBinary(Sequence, Sequence106, Action107);
	oop Definition109 = newBinary(Definition, Identifier98, Sequence108);
	addRuleDefinitionToGrammar(grammar, Definition109);

	oop Identifier110 = newIdentifier("prefix");
	oop Identifier111 = newIdentifier("AND");
	oop Identifier112 = newIdentifier("action");
	oop Sequence113 = newBinary(Sequence, Identifier111, Identifier112);
	oop Identifier114 = newIdentifier("AND");
	oop Identifier115 = newIdentifier("s");
	oop Identifier116 = newIdentifier("suffix");
	oop Assignment117 = newBinary(Assignment, Identifier115, Identifier116);
	oop Sequence118 = newBinary(Sequence, Identifier114, Assignment117);
	oop Action119 = newAction(" $$ = newUnary(And, s); ");
	oop Sequence120 = newBinary(Sequence, Sequence118, Action119);
	oop Identifier121 = newIdentifier("NOT");
	oop Identifier122 = newIdentifier("s");
	oop Identifier123 = newIdentifier("suffix");
	oop Assignment124 = newBinary(Assignment, Identifier122, Identifier123);
	oop Sequence125 = newBinary(Sequence, Identifier121, Assignment124);
	oop Action126 = newAction(" $$ = newUnary(Not, s); ");
	oop Sequence127 = newBinary(Sequence, Sequence125, Action126);
	oop Alternation128 = newBinary(Alternation, Sequence120, Sequence127);
	oop Identifier129 = newIdentifier("s");
	oop Identifier130 = newIdentifier("suffix");
	oop Assignment131 = newBinary(Assignment, Identifier129, Identifier130);
	oop Action132 = newAction(" $$ = s; ");
	oop Sequence133 = newBinary(Sequence, Assignment131, Action132);
	oop Alternation134 = newBinary(Alternation, Alternation128, Sequence133);
	oop Alternation135 = newBinary(Alternation, Sequence113, Alternation134);
	oop Definition136 = newBinary(Definition, Identifier110, Alternation135);
	addRuleDefinitionToGrammar(grammar, Definition136);

	oop Identifier137 = newIdentifier("suffix");
	oop Identifier138 = newIdentifier("p");
	oop Identifier139 = newIdentifier("primary");
	oop Assignment140 = newBinary(Assignment, Identifier138, Identifier139);
	oop Identifier141 = newIdentifier("QUERY");
	oop Action142 = newAction(" p = newUnary(Optional, p); ");
	oop Sequence143 = newBinary(Sequence, Identifier141, Action142);
	oop Identifier144 = newIdentifier("STAR");
	oop Action145 = newAction(" p = newUnary(Star, p); ");
	oop Sequence146 = newBinary(Sequence, Identifier144, Action145);
	oop Alternation147 = newBinary(Alternation, Sequence143, Sequence146);
	oop Identifier148 = newIdentifier("PLUS");
	oop Action149 = newAction(" p = newUnary(Plus, p); ");
	oop Sequence150 = newBinary(Sequence, Identifier148, Action149);
	oop Alternation151 = newBinary(Alternation, Alternation147, Sequence150);
	oop Optional152 = newUnary(Optional, Alternation151);
	oop Sequence153 = newBinary(Sequence, Assignment140, Optional152);
	oop Action154 = newAction(" $$ = p; ");
	oop Sequence155 = newBinary(Sequence, Sequence153, Action154);
	oop Definition156 = newBinary(Definition, Identifier137, Sequence155);
	addRuleDefinitionToGrammar(grammar, Definition156);

	oop Identifier157 = newIdentifier("primary");
	oop Identifier158 = newIdentifier("i1");
	oop Identifier159 = newIdentifier("identifier");
	oop Assignment160 = newBinary(Assignment, Identifier158, Identifier159);
	oop Identifier161 = newIdentifier("COLON");
	oop Sequence162 = newBinary(Sequence, Assignment160, Identifier161);
	oop Identifier163 = newIdentifier("i2");
	oop Identifier164 = newIdentifier("identifier");
	oop Assignment165 = newBinary(Assignment, Identifier163, Identifier164);
	oop Sequence166 = newBinary(Sequence, Sequence162, Assignment165);
	oop Identifier167 = newIdentifier("EQUAL");
	oop Not168 = newUnary(Not, Identifier167);
	oop Sequence169 = newBinary(Sequence, Sequence166, Not168);
	oop Action170 = newAction(" $$ = newBinary(Assignment, i1, i2) ");
	oop Sequence171 = newBinary(Sequence, Sequence169, Action170);
	oop Identifier172 = newIdentifier("i");
	oop Identifier173 = newIdentifier("identifier");
	oop Assignment174 = newBinary(Assignment, Identifier172, Identifier173);
	oop Identifier175 = newIdentifier("EQUAL");
	oop Not176 = newUnary(Not, Identifier175);
	oop Sequence177 = newBinary(Sequence, Assignment174, Not176);
	oop Action178 = newAction(" $$ = i; ");
	oop Sequence179 = newBinary(Sequence, Sequence177, Action178);
	oop Alternation180 = newBinary(Alternation, Sequence171, Sequence179);
	oop Identifier181 = newIdentifier("OPEN");
	oop Identifier182 = newIdentifier("e");
	oop Identifier183 = newIdentifier("expression");
	oop Assignment184 = newBinary(Assignment, Identifier182, Identifier183);
	oop Sequence185 = newBinary(Sequence, Identifier181, Assignment184);
	oop Identifier186 = newIdentifier("CLOSE");
	oop Sequence187 = newBinary(Sequence, Sequence185, Identifier186);
	oop Action188 = newAction(" $$ = e; ");
	oop Sequence189 = newBinary(Sequence, Sequence187, Action188);
	oop Alternation190 = newBinary(Alternation, Alternation180, Sequence189);
	oop Identifier191 = newIdentifier("l");
	oop Identifier192 = newIdentifier("literal");
	oop Assignment193 = newBinary(Assignment, Identifier191, Identifier192);
	oop Action194 = newAction(" $$ = l; ");
	oop Sequence195 = newBinary(Sequence, Assignment193, Action194);
	oop Alternation196 = newBinary(Alternation, Alternation190, Sequence195);
	oop Identifier197 = newIdentifier("c");
	oop Identifier198 = newIdentifier("class");
	oop Assignment199 = newBinary(Assignment, Identifier197, Identifier198);
	oop Action200 = newAction(" $$ = c; ");
	oop Sequence201 = newBinary(Sequence, Assignment199, Action200);
	oop Alternation202 = newBinary(Alternation, Alternation196, Sequence201);
	oop Identifier203 = newIdentifier("DOT");
	oop Action204 = newAction(" $$ = newDot(); ");
	oop Sequence205 = newBinary(Sequence, Identifier203, Action204);
	oop Alternation206 = newBinary(Alternation, Alternation202, Sequence205);
	oop Identifier207 = newIdentifier("a");
	oop Identifier208 = newIdentifier("action");
	oop Assignment209 = newBinary(Assignment, Identifier207, Identifier208);
	oop Action210 = newAction(" $$ = a; ");
	oop Sequence211 = newBinary(Sequence, Assignment209, Action210);
	oop Alternation212 = newBinary(Alternation, Alternation206, Sequence211);
	oop Identifier213 = newIdentifier("BEGIN");
	oop Action214 = newAction(" $$ = newBegin(); ");
	oop Sequence215 = newBinary(Sequence, Identifier213, Action214);
	oop Alternation216 = newBinary(Alternation, Alternation212, Sequence215);
	oop Identifier217 = newIdentifier("END");
	oop Action218 = newAction(" $$ = newEnd(); ");
	oop Sequence219 = newBinary(Sequence, Identifier217, Action218);
	oop Alternation220 = newBinary(Alternation, Alternation216, Sequence219);
	oop Definition221 = newBinary(Definition, Identifier157, Alternation220);
	addRuleDefinitionToGrammar(grammar, Definition221);

	oop Identifier222 = newIdentifier("identifier");
	oop Begin223 = newBegin();
	oop CharacterClass224 = newCharacterClass("-a-zA-Z_");
	oop Sequence225 = newBinary(Sequence, Begin223, CharacterClass224);
	oop CharacterClass226 = newCharacterClass("-a-zA-Z_0-9");
	oop Star227 = newUnary(Star, CharacterClass226);
	oop Sequence228 = newBinary(Sequence, Sequence225, Star227);
	oop End229 = newEnd();
	oop Sequence230 = newBinary(Sequence, Sequence228, End229);
	oop Identifier231 = newIdentifier("-");
	oop Sequence232 = newBinary(Sequence, Sequence230, Identifier231);
	oop Action233 = newAction(" $$ = newIdentifier(yytext); ");
	oop Sequence234 = newBinary(Sequence, Sequence232, Action233);
	oop Definition235 = newBinary(Definition, Identifier222, Sequence234);
	addRuleDefinitionToGrammar(grammar, Definition235);

	oop Identifier236 = newIdentifier("literal");
	oop CharacterClass237 = newCharacterClass("\'");
	oop Begin238 = newBegin();
	oop Sequence239 = newBinary(Sequence, CharacterClass237, Begin238);
	oop CharacterClass240 = newCharacterClass("\'");
	oop Not241 = newUnary(Not, CharacterClass240);
	oop Identifier242 = newIdentifier("char");
	oop Sequence243 = newBinary(Sequence, Not241, Identifier242);
	oop Star244 = newUnary(Star, Sequence243);
	oop Sequence245 = newBinary(Sequence, Sequence239, Star244);
	oop End246 = newEnd();
	oop Sequence247 = newBinary(Sequence, Sequence245, End246);
	oop CharacterClass248 = newCharacterClass("\'");
	oop Sequence249 = newBinary(Sequence, Sequence247, CharacterClass248);
	oop Identifier250 = newIdentifier("-");
	oop Sequence251 = newBinary(Sequence, Sequence249, Identifier250);
	oop Action252 = newAction(" $$ = newString(yytext); ");
	oop Sequence253 = newBinary(Sequence, Sequence251, Action252);
	oop CharacterClass254 = newCharacterClass("\"");
	oop Begin255 = newBegin();
	oop Sequence256 = newBinary(Sequence, CharacterClass254, Begin255);
	oop CharacterClass257 = newCharacterClass("\"");
	oop Not258 = newUnary(Not, CharacterClass257);
	oop Identifier259 = newIdentifier("char");
	oop Sequence260 = newBinary(Sequence, Not258, Identifier259);
	oop Star261 = newUnary(Star, Sequence260);
	oop Sequence262 = newBinary(Sequence, Sequence256, Star261);
	oop End263 = newEnd();
	oop Sequence264 = newBinary(Sequence, Sequence262, End263);
	oop CharacterClass265 = newCharacterClass("\"");
	oop Sequence266 = newBinary(Sequence, Sequence264, CharacterClass265);
	oop Identifier267 = newIdentifier("-");
	oop Sequence268 = newBinary(Sequence, Sequence266, Identifier267);
	oop Alternation269 = newBinary(Alternation, Sequence253, Sequence268);
	oop Definition270 = newBinary(Definition, Identifier236, Alternation269);
	addRuleDefinitionToGrammar(grammar, Definition270);

	oop Identifier271 = newIdentifier("class");
	oop String272 = newString("[");
	oop Begin273 = newBegin();
	oop Sequence274 = newBinary(Sequence, String272, Begin273);
	oop String275 = newString("]");
	oop Not276 = newUnary(Not, String275);
	oop Identifier277 = newIdentifier("range");
	oop Sequence278 = newBinary(Sequence, Not276, Identifier277);
	oop Star279 = newUnary(Star, Sequence278);
	oop Sequence280 = newBinary(Sequence, Sequence274, Star279);
	oop End281 = newEnd();
	oop Sequence282 = newBinary(Sequence, Sequence280, End281);
	oop String283 = newString("]");
	oop Sequence284 = newBinary(Sequence, Sequence282, String283);
	oop Identifier285 = newIdentifier("-");
	oop Sequence286 = newBinary(Sequence, Sequence284, Identifier285);
	oop Action287 = newAction(" $$ = newCharacterClass(yytext); ");
	oop Sequence288 = newBinary(Sequence, Sequence286, Action287);
	oop Definition289 = newBinary(Definition, Identifier271, Sequence288);
	addRuleDefinitionToGrammar(grammar, Definition289);

	oop Identifier290 = newIdentifier("range");
	oop Identifier291 = newIdentifier("char");
	oop String292 = newString("-");
	oop Sequence293 = newBinary(Sequence, Identifier291, String292);
	oop Identifier294 = newIdentifier("char");
	oop Sequence295 = newBinary(Sequence, Sequence293, Identifier294);
	oop Identifier296 = newIdentifier("char");
	oop Alternation297 = newBinary(Alternation, Sequence295, Identifier296);
	oop Definition298 = newBinary(Definition, Identifier290, Alternation297);
	addRuleDefinitionToGrammar(grammar, Definition298);

	oop Identifier299 = newIdentifier("char");
	oop String300 = newString("\\\\");
	oop CharacterClass301 = newCharacterClass("abefnrtv\'\"\\[\\]\\\\");
	oop Sequence302 = newBinary(Sequence, String300, CharacterClass301);
	oop String303 = newString("\\\\");
	oop CharacterClass304 = newCharacterClass("0-3");
	oop Sequence305 = newBinary(Sequence, String303, CharacterClass304);
	oop CharacterClass306 = newCharacterClass("0-7");
	oop Sequence307 = newBinary(Sequence, Sequence305, CharacterClass306);
	oop CharacterClass308 = newCharacterClass("0-7");
	oop Sequence309 = newBinary(Sequence, Sequence307, CharacterClass308);
	oop Alternation310 = newBinary(Alternation, Sequence302, Sequence309);
	oop String311 = newString("\\\\");
	oop CharacterClass312 = newCharacterClass("0-7");
	oop Sequence313 = newBinary(Sequence, String311, CharacterClass312);
	oop CharacterClass314 = newCharacterClass("0-7");
	oop Optional315 = newUnary(Optional, CharacterClass314);
	oop Sequence316 = newBinary(Sequence, Sequence313, Optional315);
	oop Alternation317 = newBinary(Alternation, Alternation310, Sequence316);
	oop String318 = newString("\\\\");
	oop Not319 = newUnary(Not, String318);
	oop Dot320 = newDot();
	oop Sequence321 = newBinary(Sequence, Not319, Dot320);
	oop Alternation322 = newBinary(Alternation, Alternation317, Sequence321);
	oop Definition323 = newBinary(Definition, Identifier299, Alternation322);
	addRuleDefinitionToGrammar(grammar, Definition323);

	oop Identifier324 = newIdentifier("action");
	oop String325 = newString("{");
	oop Begin326 = newBegin();
	oop Sequence327 = newBinary(Sequence, String325, Begin326);
	oop Identifier328 = newIdentifier("braces");
	oop Star329 = newUnary(Star, Identifier328);
	oop Sequence330 = newBinary(Sequence, Sequence327, Star329);
	oop End331 = newEnd();
	oop Sequence332 = newBinary(Sequence, Sequence330, End331);
	oop String333 = newString("}");
	oop Sequence334 = newBinary(Sequence, Sequence332, String333);
	oop Identifier335 = newIdentifier("-");
	oop Sequence336 = newBinary(Sequence, Sequence334, Identifier335);
	oop Action337 = newAction(" $$ = newAction(yytext); ");
	oop Sequence338 = newBinary(Sequence, Sequence336, Action337);
	oop Definition339 = newBinary(Definition, Identifier324, Sequence338);
	addRuleDefinitionToGrammar(grammar, Definition339);

	oop Identifier340 = newIdentifier("braces");
	oop String341 = newString("{");
	oop Identifier342 = newIdentifier("braces");
	oop Star343 = newUnary(Star, Identifier342);
	oop Sequence344 = newBinary(Sequence, String341, Star343);
	oop String345 = newString("}");
	oop Sequence346 = newBinary(Sequence, Sequence344, String345);
	oop String347 = newString("}");
	oop Not348 = newUnary(Not, String347);
	oop Dot349 = newDot();
	oop Sequence350 = newBinary(Sequence, Not348, Dot349);
	oop Alternation351 = newBinary(Alternation, Sequence346, Sequence350);
	oop Definition352 = newBinary(Definition, Identifier340, Alternation351);
	addRuleDefinitionToGrammar(grammar, Definition352);

	oop Identifier353 = newIdentifier("EQUAL");
	oop String354 = newString("=");
	oop Identifier355 = newIdentifier("-");
	oop Sequence356 = newBinary(Sequence, String354, Identifier355);
	oop Definition357 = newBinary(Definition, Identifier353, Sequence356);
	addRuleDefinitionToGrammar(grammar, Definition357);

	oop Identifier358 = newIdentifier("COLON");
	oop String359 = newString(":");
	oop Identifier360 = newIdentifier("-");
	oop Sequence361 = newBinary(Sequence, String359, Identifier360);
	oop Definition362 = newBinary(Definition, Identifier358, Sequence361);
	addRuleDefinitionToGrammar(grammar, Definition362);

	oop Identifier363 = newIdentifier("SEMICOLON");
	oop String364 = newString(";");
	oop Identifier365 = newIdentifier("-");
	oop Sequence366 = newBinary(Sequence, String364, Identifier365);
	oop Definition367 = newBinary(Definition, Identifier363, Sequence366);
	addRuleDefinitionToGrammar(grammar, Definition367);

	oop Identifier368 = newIdentifier("BAR");
	oop String369 = newString("|");
	oop Identifier370 = newIdentifier("-");
	oop Sequence371 = newBinary(Sequence, String369, Identifier370);
	oop Definition372 = newBinary(Definition, Identifier368, Sequence371);
	addRuleDefinitionToGrammar(grammar, Definition372);

	oop Identifier373 = newIdentifier("AND");
	oop String374 = newString("&");
	oop Identifier375 = newIdentifier("-");
	oop Sequence376 = newBinary(Sequence, String374, Identifier375);
	oop Definition377 = newBinary(Definition, Identifier373, Sequence376);
	addRuleDefinitionToGrammar(grammar, Definition377);

	oop Identifier378 = newIdentifier("NOT");
	oop String379 = newString("!");
	oop Identifier380 = newIdentifier("-");
	oop Sequence381 = newBinary(Sequence, String379, Identifier380);
	oop Definition382 = newBinary(Definition, Identifier378, Sequence381);
	addRuleDefinitionToGrammar(grammar, Definition382);

	oop Identifier383 = newIdentifier("QUERY");
	oop String384 = newString("?");
	oop Identifier385 = newIdentifier("-");
	oop Sequence386 = newBinary(Sequence, String384, Identifier385);
	oop Definition387 = newBinary(Definition, Identifier383, Sequence386);
	addRuleDefinitionToGrammar(grammar, Definition387);

	oop Identifier388 = newIdentifier("STAR");
	oop String389 = newString("*");
	oop Identifier390 = newIdentifier("-");
	oop Sequence391 = newBinary(Sequence, String389, Identifier390);
	oop Definition392 = newBinary(Definition, Identifier388, Sequence391);
	addRuleDefinitionToGrammar(grammar, Definition392);

	oop Identifier393 = newIdentifier("PLUS");
	oop String394 = newString("+");
	oop Identifier395 = newIdentifier("-");
	oop Sequence396 = newBinary(Sequence, String394, Identifier395);
	oop Definition397 = newBinary(Definition, Identifier393, Sequence396);
	addRuleDefinitionToGrammar(grammar, Definition397);

	oop Identifier398 = newIdentifier("OPEN");
	oop String399 = newString("(");
	oop Identifier400 = newIdentifier("-");
	oop Sequence401 = newBinary(Sequence, String399, Identifier400);
	oop Definition402 = newBinary(Definition, Identifier398, Sequence401);
	addRuleDefinitionToGrammar(grammar, Definition402);

	oop Identifier403 = newIdentifier("CLOSE");
	oop String404 = newString(")");
	oop Identifier405 = newIdentifier("-");
	oop Sequence406 = newBinary(Sequence, String404, Identifier405);
	oop Definition407 = newBinary(Definition, Identifier403, Sequence406);
	addRuleDefinitionToGrammar(grammar, Definition407);

	oop Identifier408 = newIdentifier("DOT");
	oop String409 = newString(".");
	oop Identifier410 = newIdentifier("-");
	oop Sequence411 = newBinary(Sequence, String409, Identifier410);
	oop Definition412 = newBinary(Definition, Identifier408, Sequence411);
	addRuleDefinitionToGrammar(grammar, Definition412);

	oop Identifier413 = newIdentifier("BEGIN");
	oop String414 = newString("<");
	oop Identifier415 = newIdentifier("-");
	oop Sequence416 = newBinary(Sequence, String414, Identifier415);
	oop Definition417 = newBinary(Definition, Identifier413, Sequence416);
	addRuleDefinitionToGrammar(grammar, Definition417);

	oop Identifier418 = newIdentifier("END");
	oop String419 = newString(">");
	oop Identifier420 = newIdentifier("-");
	oop Sequence421 = newBinary(Sequence, String419, Identifier420);
	oop Definition422 = newBinary(Definition, Identifier418, Sequence421);
	addRuleDefinitionToGrammar(grammar, Definition422);

	oop Identifier423 = newIdentifier("TILDE");
	oop String424 = newString("~");
	oop Identifier425 = newIdentifier("-");
	oop Sequence426 = newBinary(Sequence, String424, Identifier425);
	oop Definition427 = newBinary(Definition, Identifier423, Sequence426);
	addRuleDefinitionToGrammar(grammar, Definition427);

	oop Identifier428 = newIdentifier("RPERCENT");
	oop String429 = newString("%}");
	oop Identifier430 = newIdentifier("-");
	oop Sequence431 = newBinary(Sequence, String429, Identifier430);
	oop Definition432 = newBinary(Definition, Identifier428, Sequence431);
	addRuleDefinitionToGrammar(grammar, Definition432);

	oop Identifier433 = newIdentifier("-");
	oop Identifier434 = newIdentifier("space");
	oop Identifier435 = newIdentifier("comment");
	oop Alternation436 = newBinary(Alternation, Identifier434, Identifier435);
	oop Star437 = newUnary(Star, Alternation436);
	oop Definition438 = newBinary(Definition, Identifier433, Star437);
	addRuleDefinitionToGrammar(grammar, Definition438);

	oop Identifier439 = newIdentifier("space");
	oop String440 = newString(" ");
	oop String441 = newString("\\t");
	oop Alternation442 = newBinary(Alternation, String440, String441);
	oop Identifier443 = newIdentifier("end-of-line");
	oop Alternation444 = newBinary(Alternation, Alternation442, Identifier443);
	oop Definition445 = newBinary(Definition, Identifier439, Alternation444);
	addRuleDefinitionToGrammar(grammar, Definition445);

	oop Identifier446 = newIdentifier("comment");
	oop String447 = newString("#");
	oop Identifier448 = newIdentifier("end-of-line");
	oop Not449 = newUnary(Not, Identifier448);
	oop Dot450 = newDot();
	oop Sequence451 = newBinary(Sequence, Not449, Dot450);
	oop Star452 = newUnary(Star, Sequence451);
	oop Sequence453 = newBinary(Sequence, String447, Star452);
	oop Identifier454 = newIdentifier("end-of-line");
	oop Sequence455 = newBinary(Sequence, Sequence453, Identifier454);
	oop Definition456 = newBinary(Definition, Identifier446, Sequence455);
	addRuleDefinitionToGrammar(grammar, Definition456);

	oop Identifier457 = newIdentifier("end-of-line");
	oop String458 = newString("\\r\\n");
	oop String459 = newString("\\n");
	oop Alternation460 = newBinary(Alternation, String458, String459);
	oop String461 = newString("\\r");
	oop Alternation462 = newBinary(Alternation, Alternation460, String461);
	oop Definition463 = newBinary(Definition, Identifier457, Alternation462);
	addRuleDefinitionToGrammar(grammar, Definition463);

	oop Identifier464 = newIdentifier("end-of-file");
	oop Dot465 = newDot();
	oop Not466 = newUnary(Not, Dot465);
	oop Definition467 = newBinary(Definition, Identifier464, Not466);
	addRuleDefinitionToGrammar(grammar, Definition467);

	return grammar;
}
